### ISSUE TITLE
Check Like filter with iterable data provider

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/data#101]
Data:

- Alexander
- Alexey
- Boris
- Alena

Filter:

- Ale

Output:

- Alexander
- Alexey
- Alena

**Comment by samdark** [comment]
Checked it. Works. Also, there is a test for it:

https://github.com/yiisoft/data/blob/9158a12f1eae022a733a7ff9cb2a19eecac5bd94/tests/Reader/IterableDataReaderTest.php#L243
