### ISSUE TITLE
Paginator refactoring concept

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#111]
Implementations of `PaginatorInterface` is very different. Some methods need in one implementation, and not need in other implementations. Some methods should named different in different implementations. Seems `PaginatorInterface` not need.

Suggest:
- remove `PaginationInterface`;
- remove from paginator implementation any "read" functional;
- add to paginator implementation new method `getFilter(): FilterInterface` that contains pagination logic in the form of a filter;
- usage result of `getFilter()` method in reader.

Example:

```php
$pagination = (new KeysetPaginator($dataReader))->withPageSize(10);

$filter = new All($myFilter1, $myFilter2, $pagination->getFilter());

$reader = (new IterableDataReader($myDataSet))->withFilter($filter);

$result = $reader->read();
```

**Comment by vjik** [comment]
I'm researched problem and extracted interface removal to separate issue: https://github.com/yiisoft/data/issues/112.

**Comment by samdark** [comment]
> remove from paginator implementation any "read" functional;

Why? The paginator was created as a decorator for data reader. I don't think introducing additional concept of a filter makes the whole thing easier.
