### ISSUE TITLE
IterableDataReader::count(): Not handled if not \Countable.

### ISSUE THREAD

**Issue by kamarton** [yiisoft/data#12]
### What steps will reproduce the problem?

`IterableDataReader#data` is `iterable` type, but [count()](https://www.php.net/manual/en/function.count.php) support only `array` and `\Countable`.

### What is the expected result?

```php
$reader = IterableDataReader(new class implements \Iterator { ... });
var_dump($reader->count());     // throw not supported exception
```

### What do you get instead?

```php
$reader = IterableDataReader(new class implements \Iterator { ... });
var_dump($reader->count());
// PHP Warning:  count(): Parameter must be an array or an object that implements Countable in Command line code on line 1
// int(1)
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0
| PHP version      | -
| Operating system | -

**Comment by pchapl** [comment]
Easy to fix: there are `\Yiisoft\Data\Reader\IterableDataReader::iterableToArray` method
```
public function count(): int
{
-    return count($this->read());
+    return count($this->iterableToArray($this->data));
}
```
