### ISSUE TITLE
Improve namespacing

### ISSUE THREAD

**Issue by samdark** [yiisoft/data#120]
- [x] Move Reader\Interable to IterableReader to separate concepts better.
- [x] Merge FilterHandlerInterface into IterableHandlerInterface since it's used in iterable filter only.

**Comment by vjik** [comment]
> Merge FilterHandlerInterface into IterableHandlerInterface since it's used in iterable filter only.

`FilterHandlerInterface` used in common reader interface [FilterableDataInterface](https://github.com/yiisoft/data/blob/1f27ac57bdd0e3635fa74c850e4de0ec770eb4f8/src/Reader/FilterableDataInterface.php#L14).
