### ISSUE TITLE
Move `FilterDataValidationHelper::assertFilterHandlerIsIterable()` method to `Iterable` namespace

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#121]
`FilterDataValidationHelper` contains common reader methods. `assertFilterHandlerIsIterable()` used for iterable reader only and should be moved to `Iterable` namespace.

**Comment by vjik** [comment]
Not fixed

**Comment by samdark** [comment]
It is alright as is since the `FilterAssert` is used everywhere.
