### ISSUE TITLE
Throws exception when pass to `IterableDataReader` non-`IterableFilterHandlerInterface` filter handlers

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#124]

**Comment by samdark** [comment]
Do you mean throwing exception here? https://github.com/yiisoft/data/blob/master/src/Reader/Iterable/IterableDataReader.php#L93

**Comment by vjik** [comment]
> Do you mean throwing exception here? https://github.com/yiisoft/data/blob/master/src/Reader/Iterable/IterableDataReader.php#L93

Yes
