### ISSUE TITLE
Make accessing item methods explicit or not?

### ISSUE THREAD

**Issue by samdark** [yiisoft/data#127]
# What's wrong?

Currently there is [getters and setters support in KeysetPaginator](https://github.com/yiisoft/data/blob/52075a2a3808d2e6cef9a5896e06e5688eac295c/src/Paginator/KeysetPaginator.php#L305). There's no such thing in other data readers.

# Fix 1

We could make these explicit i.e. if you need a getter you state it specifically such as `getName()`. Note the `()`. We won't check existence of the method via reflection and won't inflect the name. Just call it directly.

Advantages:

- Explicit.
- Good performance.

Disadvantages:

- Method names will get into URLs when using filters.

# Fix 2

Alternative is to extract inflector and reflection based magic from KeysetPaginator and use it everywhere.

Advantages:

- URLs will be short and nice.

Disadvantages:

- Magic.
- Lower performance.

**Comment by vjik** [comment]
My choice — "Fix 1"

**Comment by samdark** [comment]
Same here. "Fix 1" looks way better.
