### ISSUE TITLE
Finalize `IterableDataReader`

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#130]

**Comment by samdark** [comment]
Inheritance is used in tests and, I think, these are valid cases for apps as well:

https://github.com/yiisoft/data/search?q="extends+IterableDataReader"

**Comment by vjik** [comment]
After https://github.com/yiisoft/data/pull/129 inheritance of `IterableDataReader` will not be used. If required in app, we can always definilize class. So far, there are no cases, right?

**Comment by samdark** [comment]
Well, if you can rewrite tests w/o using it then yes.

**Comment by vjik** [comment]
Closed by #132
