### ISSUE TITLE
Allow building criteria with arrays

### ISSUE THREAD

**Issue by samdark** [yiisoft/data#15]
Syntax could be something like:

```php
$filter = $aaa->where([
  ['and', 'id', '>', 3],
  ['and', ['or', ['temperature', '<', 10], ['temperature', '>', 30]] ],
  ['and', 'name', like', '%agent%'],
];
```

See https://yiiframework.ru/forum/viewtopic.php?f=39&t=52964

**Comment by pchapl** [comment]
There already is "filter to array" transformation in `IterableDataReader`:
```php
$filter = null;
if ($this->filter !== null) {
    $filter = $this->filter->toArray();
}
```
Could be replaced with
```php
$filter = $this->filter instanceof FilterInterface
    ? $this->filter->toArray()
    : $this->filter;
```
So well-formed filter will work properly. But there will be problems with incorrect filters (kind of `['and', 'id', '>']`) and will require some extra validation.

**Comment by romkatsu** [comment]
@pchapl Yes, objects are better. But it seems here the speech about that there was an opportunity to use arrays.

**Comment by samdark** [comment]
It is more about working with a special filter string that comes from request like it's done for sorting.

In Yii 2 REST APIs there was ability to specify filtering as JSON.

Requirements are:

1. It should be as short as possible.
2. It should be readable.
3. Some filters could be disabled for some fields (tricky part).

**Comment by samdark** [comment]
Overall, it can be done with a separate component so could be safely postponed or done in another package such as GridView.

**Comment by kamarton** [comment]
```php
$filter = $aaa->where([
  ['and', 'id', '>', 3],
  ['and', ['or', ['temperature', '<', 10], ['temperature', '>', 30]] ],
  ['and', 'name', like', '%agent%'],
];
```

I would limit the use of this to simplify code.

```php
$filter = new All()->withArray([
  ['<', 'id', 22],
  ['or',
    ['>', 'apple', 33],
    ['!=', 'peach', 44], 
  ]
])

$filter = new Any(
  new All(new Equals(), ...),
  new All()->withArray([...]),
)
```

Arrays would be limited to the `All` class, this method would allow all kinds of use. The `All` class is working on arrays, so much easier code is created.

**Comment by samdark** [comment]
All or Any. Yes, good idea.
