### ISSUE TITLE
Paginators must take into account limit in decorated data reader

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#187]
See https://github.com/yiisoft/yii-dataview/issues/7

**Comment by samdark** [comment]
Could be implemented for `OffsetPaginator` but can't for `KeysetPaginator` since we have no idea how many items we've already skipped.

**Comment by vjik** [comment]
Suggest implement it in `OffsetPaginator`, but in `KeysetPaginator` throw `LogicException` when passed data reader with limit.
