### ISSUE TITLE
Add `bool $prepare = false` parameter to `OffsetPaginator::withCurrentPage()` method

### ISSUE THREAD

**Issue by vjik** [yiisoft/data#206]
When `$prepare` is true, it need to check that current page is correct (1 <= current page <= max page), and set current page as 1 if current page is incorrect.

**Comment by vjik** [comment]
Bad idea. Theoretically, we can set page size after set current page.

**Comment by TiaNex-Com** [comment]
public function withCurrentPage(int $page): self
    {
        if ($page < 1) {
            throw new PaginatorException('Current page should be at least 1.');
        }
 
      if($page>$this->getTotalPages()){
        $page = getTotalPages(); 
      }
 

        $new = clone $this;
        $new->token = PageToken::next((string) $page);
        return $new;
    }


when the page > max page number ,then set the page=max page number, that may cause duplicated page problem (it's affact  little for SEO ?)  ,but better than 404,or 500 error, i think

**Comment by samdark** [comment]
404 is ideal for the case.

**Comment by TiaNex-Com** [comment]
> 404 is ideal for the case.

maybe not, for example a product list,  there is no page 3, but after i add some products,  page 3 have products now,
if we have sent 404 to search engine,  search engine won't index new products,

i don't know which way is better,
