### ISSUE TITLE
incorrect namespace

### ISSUE THREAD

**Issue by kamarton** [yiisoft/data#22]
These interfaces and functions are incorrectly placed under the "Reader" namespace because they can also be used for `Writer`:
- `src/Reader/Filter`
- `src/Reader/SortableDataInterface.php`
- `src/Reader/FilterableDataInterface.php`
- `src/Reader/Sort.php`
- [`DataReaderInterface#withLimit()`](https://github.com/yiisoft/data/blob/3d4a407268d6712d375662b9c409bc854bb2dcbe/src/Reader/DataReaderInterface.php#L14)

Example SQL update:
```sql
UPDATE `table` SET values... WHERE <filters> ORDER BY <sorters> LIMIT <limit>
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0 under development
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
and `\Yiisoft\Data\Reader\OffsetableDataInterface`: mongodb support inserting at position (see [`$position`](https://docs.mongodb.com/manual/reference/operator/update/position/)). I can imagine that there is an API endpoint that can write to a position similarly.

**Comment by samdark** [comment]
While such SQL makes sense, I see no use for filtering in case of writer. We have data we want to write already, it's easier and more efficient to filter data with simple foreach than by passing unfiltered data array to writer along with saving criteria.

**Comment by rob006** [comment]
> Example SQL update:

This looks like MySQL-specific. AFAIK limit and order are not directly supported in update queries by most of DBMS.

**Comment by kamarton** [comment]
@rob006 This is a generic Writer layer, if you have the opportunity somewhere, it is advisable to plan into the layer.

**Comment by samdark** [comment]
I still don't see any practical application for using filters with a data writer. We have our data, we can prepare it right away **before** sending it to writer. That has both simplicity and performance benefits.

**Comment by kamarton** [comment]
I can't really see what the Writer interface is all about. I assumed that ActiveRecord would use this too, hiding the write layer, e.g. so that I can swap one NoSQL under it for another NoSQL without changing ActiveRecord class.

```php
$ar->field2 = '22';
$ar->save();

// $ar->save() --> $db->writer() -> writer->write();
$db->writer->withFilters(new Equals('id',  $ar->id))->write($ar->changedAttributes());
```

I implemented more database server under yii2, and I find this solution easier to implement and more flexible.

**Comment by samdark** [comment]
> I can't really see what the Writer interface is all about.

Having array of data items, persist all of them.

> $db->writer->withFilters(new Equals('id',  $ar->id))->write($ar->changedAttributes());

Why do you need withFilters here? Also, changed attributes isn't writer concern. That's internal thing of a possible AR specific implementation.

**Comment by kamarton** [comment]
It's ok, if run INSERT, but if require UPDATE?
```php
$writer = new ActiveRecordDataWriter(User::class);
$writer->write($data);
```

I don't really see why `Writer` filters are provided wit AR, whereas` Reader` filters are not.

```php
$db->writer->withFilters(new LessThan('id',  88))->write($attributes);
// === yii2 AR->updateAll($attributes, ['<', 'id', 88]);
```

If I use simple types, I just need to replace the `Writer` and write to almost any target destination (RDBMS, NoSQL, Redis), eg with custom BasicActiveRecord. If ActiveRecord does this (why?), Then I need to create a N versions of class because they must extends from different classes.

Nonetheless, I already understand that this is not a real `Writer` layer, but some very simplified implementation, and I probably need to see the rest of the system to understand why.

**Comment by samdark** [comment]
Yes, that wasn't meant to replace AR or provide full-featured abstraction over any storage. Let's assume it won't be needed to reuse filters for writer.
