### ISSUE TITLE
ReverseScannableDataInterface

### ISSUE THREAD

**Issue by kamarton** [yiisoft/data#23]
### What steps will reproduce the problem?

There may be times when data needs to be scanned as reversed. Currently there is no specific interface defined, but can using with reversed `Sort` orders.

- RDBMS: supported partially or with sort
- NoSQL:
  - mongoDb: supported by sort
  - Apache HBase: supported by scanner level
  - Google Bigtable: not supported

### What is the expected result?

```
$reader->withReverseScanning()->read();
```

| condition of data reader                                    | result                                                                             |
|---------------------------------------------|------------------------------------------------------------------------------------|
| if supported it, or partially supported                            | scanning in reverse mode                                                           |
| if not supported it, but supported sorting  | reverses sorting immediately before scanning                                       |
| If not supported it                         | throw exception, or<br>implement it at PHP level after reading the data, if possible. |

examples:
- if supported it or partially supported
```sql
SELECT * FROM (
    SELECT *
    FROM ...
    WHERE id > :first
    ORDER BY id DESC
) ORDER BY id ASC LIMIT 3  -- this is not real reverse scanning
```

- if not supported it, but supported sorting
exmaple in `IteratorDataReader`
- If not supported it
Depending on the number of data, use the `array_reverse()` function, but for example, if the number of data can be hundreds of millions, can decide to throw an exception based on the `withLimit()`. (typically with noSQL)

### What do you get instead?

https://github.com/yiisoft/data/blob/992a8bc48f2a5bb2293f56946eee155b05696eda/src/Paginator/KeysetPaginator.php#L70-L75

### Additional info

Also consider giving `Sort` a` withInversed() ` or `withReverseSorting()` method.

| Q                | A
| ---------------- | ---
| Version          | 1.0.0 under development
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
What's the practical use case for it? Is it going to be required in paginators?

**Comment by kamarton** [comment]
Yes, she came up with the Paginator. Unnecessary abstraction. I thought the `DataReader` layer is easier to handle reverse scanning if this is supported or not.
