### ISSUE TITLE
Add `readOne()` method in the DataReaderInterface

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/data#39]
I suggest adding a method for reading a single element in the DataReaderInterface.
This method will work in much the same way as the `read()` method with a limit of `1`, but will return not the collection of elements, but the first element.

``` php
interface DataReaderInterface
{
    public const DEFAULT_LIMIT = 10;

    public function withLimit(int $limit);
    public function read(): iterable;
    public function readOne();
}
```

**Comment by samdark** [comment]
I am fine with having it.
