### ISSUE TITLE
IterableDataReader: before slice after sort - Is this a good order?

### ISSUE THREAD

**Issue by kamarton** [yiisoft/data#9]
### What steps will reproduce the problem?

Currently, it organizes the current page, not the whole items.

https://github.com/yiisoft/data/blob/370d91731799fc222a2edce088571a2c2b636b44/src/Reader/IterableDataReader.php#L138-L158

### What is the expected result?

sort after slice

### What do you get instead?

slice after sort

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0 under development
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
You're right. That's wrong order and it seems we have not enough tests.
